Location invariant zero-mean GP modeling is the default in computer surrogate modeling and (ML) literatures.
```{r}
n <- 100
X <- matrix(seq(0, 10, length=n), ncol=1)
library(plgp)
D <- distance(X) # pairwise squared Euclidean distances 
```
```{r}
eps <- sqrt(.Machine$double.eps) 
Sigma <- exp(-D) + diag(eps, n) 
library(mvtnorm)
Y <- rmvnorm(1, sigma=Sigma)
plot(X, Y, type="l")
c(exp(-1^2), exp(-4^2))
Y <- rmvnorm(3, sigma=Sigma)
matplot(X, t(Y), type="l", ylab="Y")
```

simple 1d GP
```{r}
n <- 8
X <- matrix(seq(0, 2*pi, length=n), ncol=1)
y <- sin(X)
D <- distance(X) 
Sigma <- exp(-D) + diag(eps, ncol(D))
XX <- matrix(seq(-0.5, 2*pi + 0.5, length=100), ncol=1)
DXX <- distance(XX)
SXX <- exp(-DXX) + diag(eps, ncol(DXX))

DX <- distance(XX, X)
SX <- exp(-DX) 

Si <- solve(Sigma)
mup <- SX %*% Si %*% y
Sigmap <- SXX - SX %*% Si %*% t(SX)

YY <- rmvnorm(100, mup, Sigmap)

q1 <- mup + qnorm(0.05, 0, sqrt(diag(Sigmap)))
q2 <- mup + qnorm(0.95, 0, sqrt(diag(Sigmap)))

matplot(XX, t(YY), type="l", col="gray", lty=1, xlab="x", ylab="y")
points(X, y, pch=20, cex=2)
lines(XX, sin(XX), col="blue")
lines(XX, mup, lwd=2)
lines(XX, q1, lwd=2, lty=2, col=2)
lines(XX, q2, lwd=2, lty=2, col=2)
```


2d GP
```{r}
nx <- 20
x <- seq(0, 2, length=nx)
X <- expand.grid(x, x) # 20x20

D <- distance(X)
Sigma <- exp(-D) + diag(eps, nrow(X))

# random MVN
Y <- rmvnorm(2, sigma=Sigma)

par(mfrow=c(1,2)) 
persp(x, x, matrix(Y[1,], ncol=nx), theta=-30, phi=30, xlab="x1", 
  ylab="x2", zlab="y")
persp(x, x, matrix(Y[2,], ncol=nx), theta=-30, phi=30, xlab="x1", 
  ylab="x2", zlab="y")
```

```{r}

```

